In [20]:
from pandas import read_csv
import pandas as pd
import numpy as np

In [21]:
#filename = 'ADNI_emb_Train.csv'
filename = 'ADNI_emb_Test.csv'

df = read_csv(filename,header=0)
df

,RID,VISCODE,DX,F1,F2,F3,F4,F5,F6,F7,F8
0,4337,12,MCI,0.0,0.0,0.000000,0.000000,2.492250,0.510764,2.513053,0.0
1,4337,18,MCI,0.0,0.0,0.000000,0.000000,2.635370,0.687047,2.802760,0.0
2,6703,0,MCI,0.0,0.0,0.000000,0.000000,2.189217,0.171576,2.479807,0.0
3,6703,12,MCI,0.0,0.0,0.000000,0.000000,3.010649,0.286860,3.205661,0.0
4,4209,0,Dementia,0.0,0.0,2.191518,2.165182,2.469688,0.085153,2.578117,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2760,377,120,MCI,0.0,0.0,0.000000,0.000000,2.252745,0.000000,1.631581,0.0
2761,377,132,MCI,0.0,0.0,0.000000,0.000000,2.945043,0.343383,2.537941,0.0
2762,377,144,MCI,0.0,0.0,0.000000,0.000000,3.088345,0.000000,2.799656,0.0
2763,377,156,MCI,0.0,0.0,0.000000,0.000000,3.468333,0.616016,3.457686,0.0
2764,377,168,MCI,0.0,0.0,0.032128,0.040235,3.133694,0.905081,3.393676,0.0

In [22]:
rid = df[["RID"]]
unique_rid = rid.values
unique_rid = np.unique(unique_rid)
num_of_unique_rid = np.unique(unique_rid).shape[0]
num_of_unique_rid

398

In [23]:
#new_df = df.loc[:, ~df.columns.isin(['DX.bl', 'PTETHCAT', 'PTRACCAT'])]
#new_df = df.loc[:, df.columns != 'DX.bl']
#new_df = df[['RID', 'VISCODE', 'DX', 'PTGENDER', 'PTEDUCAT', 'APOE4', 'CDRSB', 'ADAS11', 'ADAS13', 'ADASQ4', 'MMSE']]

In [24]:
new_df = df[df.columns]
new_df

,RID,VISCODE,DX,F1,F2,F3,F4,F5,F6,F7,F8
0,4337,12,MCI,0.0,0.0,0.000000,0.000000,2.492250,0.510764,2.513053,0.0
1,4337,18,MCI,0.0,0.0,0.000000,0.000000,2.635370,0.687047,2.802760,0.0
2,6703,0,MCI,0.0,0.0,0.000000,0.000000,2.189217,0.171576,2.479807,0.0
3,6703,12,MCI,0.0,0.0,0.000000,0.000000,3.010649,0.286860,3.205661,0.0
4,4209,0,Dementia,0.0,0.0,2.191518,2.165182,2.469688,0.085153,2.578117,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2760,377,120,MCI,0.0,0.0,0.000000,0.000000,2.252745,0.000000,1.631581,0.0
2761,377,132,MCI,0.0,0.0,0.000000,0.000000,2.945043,0.343383,2.537941,0.0
2762,377,144,MCI,0.0,0.0,0.000000,0.000000,3.088345,0.000000,2.799656,0.0
2763,377,156,MCI,0.0,0.0,0.000000,0.000000,3.468333,0.616016,3.457686,0.0
2764,377,168,MCI,0.0,0.0,0.032128,0.040235,3.133694,0.905081,3.393676,0.0

In [25]:
# Rename the visit code
columns_name = list(new_df.columns)
new_df_2 = pd.DataFrame(columns = columns_name)
for i in range(len(unique_rid)):
    id_ = unique_rid[i]
    temp_data = new_df[new_df["RID"] == unique_rid[i]]
    size = (temp_data.shape)[0]        
    for j in range(size):
        temp_data.iat[j,1] = j * 6
        new_row = temp_data.iloc[j,:]
        new_df_2.loc[len(new_df_2)] = new_row
new_df_2

,RID,VISCODE,DX,F1,F2,F3,F4,F5,F6,F7,F8
0,35,0,MCI,0.0,0.0,0.000000,0.000000,2.932048,1.034585,3.193815,0.0
1,35,6,MCI,0.0,0.0,0.000000,0.000000,3.001298,0.883533,3.248472,0.0
2,35,12,MCI,0.0,0.0,0.000000,0.000000,3.649600,1.778392,3.852574,0.0
3,35,18,MCI,0.0,0.0,0.000000,0.000000,3.023738,0.887185,3.273083,0.0
4,35,24,MCI,0.0,0.0,0.000000,0.000000,2.814049,1.000492,2.864282,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2760,6658,6,Dementia,0.0,0.0,2.865285,3.163096,2.348794,0.143292,2.237542,0.0
2761,6702,0,MCI,0.0,0.0,0.783762,2.156917,1.562925,0.061287,0.330480,0.0
2762,6702,6,MCI,0.0,0.0,0.000000,2.181074,2.263492,1.408707,1.482411,0.0
2763,6703,0,MCI,0.0,0.0,0.000000,0.000000,2.189217,0.171576,2.479807,0.0
2764,6703,6,MCI,0.0,0.0,0.000000,0.000000,3.010649,0.286860,3.205661,0.0

In [26]:
# To count how many patients in each sequence length (1-28 visits)
couter_for_length_each_sequence = np.zeros((28))
for i in range(len(unique_rid)):
    temp_data = new_df_2[new_df_2["RID"] == unique_rid[i]]
    size = (temp_data.shape)[0]        
    couter_for_length_each_sequence[size-1]+=1
couter_for_length_each_sequence
summ = 0
for i in range(len(couter_for_length_each_sequence)):
    summ+=couter_for_length_each_sequence[i]
print(summ)
print(couter_for_length_each_sequence)

398.0
[ 0. 45. 38. 34. 64. 33. 44. 30. 21. 18. 17. 12. 10.  7.  4.  6.  6.  3.
  2.  3.  1.  0.  0.  0.  0.  0.  0.  0.]

In [27]:
df0_1 = pd.DataFrame(columns = columns_name)
df0_2 = pd.DataFrame(columns = columns_name)
df0_3 = pd.DataFrame(columns = columns_name)
df0_4 = pd.DataFrame(columns = columns_name)
df0_5 = pd.DataFrame(columns = columns_name)
df0_6 = pd.DataFrame(columns = columns_name)
df0_7 = pd.DataFrame(columns = columns_name)
df0_8 = pd.DataFrame(columns = columns_name)
df0_9 = pd.DataFrame(columns = columns_name)
df0_10 = pd.DataFrame(columns = columns_name)
df0_11 = pd.DataFrame(columns = columns_name)
df0_12 = pd.DataFrame(columns = columns_name)
df0_13 = pd.DataFrame(columns = columns_name)
df0_14 = pd.DataFrame(columns = columns_name)
df0_15 = pd.DataFrame(columns = columns_name)
df0_16 = pd.DataFrame(columns = columns_name)
df0_17 = pd.DataFrame(columns = columns_name)
df0_18 = pd.DataFrame(columns = columns_name)
df0_19 = pd.DataFrame(columns = columns_name)
df0_20 = pd.DataFrame(columns = columns_name)
df0_21 = pd.DataFrame(columns = columns_name)
df0_22 = pd.DataFrame(columns = columns_name)
for i in range(len(unique_rid)):
    temp_data = new_df_2[new_df_2["RID"] == unique_rid[i]]
    size = (temp_data.shape)[0]
    if size == 1:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_1.loc[len(df0_1)] = new_row
    elif size == 2:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_2.loc[len(df0_2)] = new_row
    elif size == 3:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_3.loc[len(df0_3)] = new_row
    elif size == 4:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_4.loc[len(df0_4)] = new_row
    elif size == 5:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_5.loc[len(df0_5)] = new_row
    elif size == 6:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_6.loc[len(df0_6)] = new_row
    elif size == 7:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_7.loc[len(df0_7)] = new_row
    elif size == 8:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_8.loc[len(df0_8)] = new_row
    elif size == 9:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_9.loc[len(df0_9)] = new_row
    elif size == 10:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_10.loc[len(df0_10)] = new_row
    elif size == 11:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_11.loc[len(df0_11)] = new_row
    elif size == 12:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_12.loc[len(df0_12)] = new_row
    elif size == 13:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_13.loc[len(df0_13)] = new_row
    elif size == 14:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_14.loc[len(df0_14)] = new_row
    elif size == 15:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_15.loc[len(df0_15)] = new_row
    elif size == 16:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_16.loc[len(df0_16)] = new_row
    elif size == 17:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_17.loc[len(df0_17)] = new_row
    elif size == 18:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_18.loc[len(df0_18)] = new_row
    elif size == 19:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_19.loc[len(df0_19)] = new_row
    elif size == 20:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_20.loc[len(df0_20)] = new_row
    elif size == 21:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_21.loc[len(df0_21)] = new_row
    elif size == 22:
        for j in range(size):
            new_row = temp_data.iloc[j,:]
            df0_22.loc[len(df0_22)] = new_row

In [28]:
df0_7

,RID,VISCODE,DX,F1,F2,F3,F4,F5,F6,F7,F8
0,102,0,MCI,0.0,0.0,0.000000,0.000000,3.609218,1.859421,3.870216,0.0
1,102,6,MCI,0.0,0.0,0.000000,0.000000,3.852039,2.281202,4.127502,0.0
2,102,12,MCI,0.0,0.0,0.000000,0.000000,1.785147,0.689433,1.771137,0.0
3,102,18,MCI,0.0,0.0,0.445149,1.144268,1.145419,0.510959,1.088403,0.0
4,102,24,MCI,0.0,0.0,1.273342,1.738623,1.440124,0.300571,1.002787,0.0
...,...,...,...,...,...,...,...,...,...,...,...
303,5119,12,Dementia,0.0,0.0,2.772128,3.305460,2.342808,0.204700,1.125973,0.0
304,5119,18,Dementia,0.0,0.0,2.622710,3.385289,2.438362,0.234712,1.382855,0.0
305,5119,24,Dementia,0.0,0.0,2.331561,3.341236,1.774691,0.528755,1.484058,0.0
306,5119,30,Dementia,0.0,0.0,2.348238,3.357181,1.786048,0.533826,1.498499,0.0
307,5119,36,Dementia,0.0,0.0,2.364915,3.373126,1.797405,0.538898,1.512941,0.0

In [29]:
list_columns = new_df_2.columns
vlaues_to_be_in_columns = []
for i in range(3, len(list_columns)):
    vlaues_to_be_in_columns.append(list_columns[i])
vlaues_to_be_in_columns.append('DX')
vlaues_to_be_in_columns
for i in range(1,23):
    if i == 1:
        df_1 = df0_1.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 2:
        df_2 = df0_2.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 3:
        df_3 = df0_3.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 4:
        df_4 = df0_4.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 5:
        df_5 = df0_5.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 6:
        df_6 = df0_6.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 7:
        df_7 = df0_7.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 8:
        df_8 = df0_8.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 9:
        df_9 = df0_9.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 10:
        df_10 = df0_10.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 11:
        df_11 = df0_11.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 12:
        df_12 = df0_12.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 13:
        df_13 = df0_13.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 14:
        df_14 = df0_14.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 15:
        df_15 = df0_15.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 16:
        df_16 = df0_16.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 17:
        df_17 = df0_17.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 18:
        df_18 = df0_18.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 19:
        df_19 = df0_19.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 20:
        df_20 = df0_20.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 21:
        df_21 = df0_21.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)
    elif i == 22:
        df_22 = df0_22.pivot(index = 'RID', columns= 'VISCODE', values= vlaues_to_be_in_columns)

In [30]:
df_9

        F1                         F2  ... F8   DX                           \
VISCODE 0  6  12 18 24 30 36 42 48 0   ... 48   0    6         12        18
RID                                    ...
128      0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI  Dementia
204      0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI  Dementia  Dementia
344      0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI  Dementia  Dementia
873      0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI  Dementia
1040     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
1218     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
2125     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
2381     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
2396     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
2398     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI  Dementia
4128     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4383     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4390     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4455     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4557     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4659     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4845     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI  Dementia
4888     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI  Dementia  Dementia
4902     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4926     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI       MCI       MCI
4928     0  0  0  0  0  0  0  0  0  0  ...  0  MCI  MCI  Dementia  Dementia


VISCODE        24        30        36        42        48
RID
128      Dementia  Dementia  Dementia  Dementia  Dementia
204      Dementia  Dementia  Dementia  Dementia  Dementia
344      Dementia  Dementia  Dementia  Dementia  Dementia
873      Dementia  Dementia  Dementia  Dementia  Dementia
1040          MCI       MCI       MCI       MCI       MCI
1218          MCI       MCI       MCI       MCI       MCI
2125          MCI       MCI       MCI       MCI       MCI
2381          MCI  Dementia  Dementia  Dementia  Dementia
2396          MCI       MCI       MCI       MCI       MCI
2398     Dementia  Dementia  Dementia  Dementia  Dementia
4128          MCI       MCI       MCI       MCI       MCI
4383          MCI       MCI       MCI       MCI       MCI
4390          MCI       MCI       MCI       MCI       MCI
4455          MCI       MCI       MCI       MCI       MCI
4557          MCI       MCI       MCI       MCI       MCI
4659          MCI       MCI  Dementia  Dementia  Dementia
4845     Dementia  Dementia  Dementia  Dementia  Dementia
4888     Dementia  Dementia  Dementia  Dementia  Dementia
4902          MCI  Dementia  Dementia  Dementia  Dementia
4926          MCI       MCI       MCI       MCI       MCI
4928     Dementia  Dementia  Dementia  Dementia  Dementia

[21 rows x 81 columns]

In [31]:
df_2.columns[1][1]

6

In [32]:
# To name the columns in the new dataset
columns_name1 = ['RID']
columns_name2 = ['RID']
columns_name3 = ['RID']
columns_name4 = ['RID']
columns_name5 = ['RID']
columns_name6 = ['RID']
columns_name7 = ['RID']
columns_name8 = ['RID']
columns_name9 = ['RID']
columns_name10 = ['RID']
columns_name11 = ['RID']
columns_name12 = ['RID']
columns_name13 = ['RID']
columns_name14 = ['RID']
columns_name15 = ['RID']
columns_name16 = ['RID']
columns_name17 = ['RID']
columns_name18 = ['RID']
columns_name19 = ['RID']
columns_name20 = ['RID']
columns_name21 = ['RID']
columns_name22 = ['RID']
for k in range(1,23):
    time_points = k #5 represents the number of time points
    for i in range(time_points):  #5 represents the number of time points
        if k == 1:
            for j in range(1, int(len(df_1.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name1.append(df_1.columns[column_idex][0] + '_'+ str(df_1.columns[column_idex][1]))
        elif k == 2:
            for j in range(1, int(len(df_2.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name2.append(df_2.columns[column_idex][0] + '_'+ str(df_2.columns[column_idex][1]))
        elif k == 3:
            for j in range(1, int(len(df_3.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name3.append(df_3.columns[column_idex][0] + '_'+ str(df_3.columns[column_idex][1]))
        elif k == 4:
            for j in range(1, int(len(df_4.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name4.append(df_4.columns[column_idex][0] + '_'+ str(df_4.columns[column_idex][1]))
        elif k == 5:
            for j in range(1, int(len(df_5.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name5.append(df_5.columns[column_idex][0] + '_'+ str(df_5.columns[column_idex][1]))
        elif k == 6:
            for j in range(1, int(len(df_6.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name6.append(df_6.columns[column_idex][0] + '_'+ str(df_6.columns[column_idex][1]))
        elif k == 7:
            for j in range(1, int(len(df_7.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name7.append(df_7.columns[column_idex][0] + '_'+ str(df_7.columns[column_idex][1]))
        elif k == 8:
            for j in range(1, int(len(df_8.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name8.append(df_8.columns[column_idex][0] + '_'+ str(df_8.columns[column_idex][1]))
        elif k == 9:
            for j in range(1, int(len(df_9.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name9.append(df_9.columns[column_idex][0] + '_'+ str(df_9.columns[column_idex][1]))
        elif k == 10:
            for j in range(1, int(len(df_10.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name10.append(df_10.columns[column_idex][0] + '_'+ str(df_10.columns[column_idex][1]))
        elif k == 11:
            for j in range(1, int(len(df_11.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name11.append(df_11.columns[column_idex][0] + '_'+ str(df_11.columns[column_idex][1]))
        elif k == 12:
            for j in range(1, int(len(df_12.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name12.append(df_12.columns[column_idex][0] + '_'+ str(df_12.columns[column_idex][1]))
        elif k == 13:
            for j in range(1, int(len(df_13.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name13.append(df_13.columns[column_idex][0] + '_'+ str(df_13.columns[column_idex][1]))
        elif k == 14:
            for j in range(1, int(len(df_14.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name14.append(df_14.columns[column_idex][0] + '_'+ str(df_14.columns[column_idex][1]))
        elif k == 15:
            for j in range(1, int(len(df_15.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name15.append(df_15.columns[column_idex][0] + '_'+ str(df_15.columns[column_idex][1]))
        elif k == 16:
            for j in range(1, int(len(df_16.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name16.append(df_16.columns[column_idex][0] + '_'+ str(df_16.columns[column_idex][1]))
        elif k == 17:
            for j in range(1, int(len(df_17.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name17.append(df_17.columns[column_idex][0] + '_'+ str(df_17.columns[column_idex][1]))
        elif k == 18:
            for j in range(1, int(len(df_18.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name18.append(df_18.columns[column_idex][0] + '_'+ str(df_18.columns[column_idex][1]))
        elif k == 19:
            for j in range(1, int(len(df_19.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name19.append(df_19.columns[column_idex][0] + '_'+ str(df_19.columns[column_idex][1]))
        elif k == 20:
            for j in range(1, int(len(df_20.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name20.append(df_20.columns[column_idex][0] + '_'+ str(df_20.columns[column_idex][1]))
        elif k == 21:
            for j in range(1, int(len(df_21.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name21.append(df_21.columns[column_idex][0] + '_'+ str(df_21.columns[column_idex][1]))
        elif k == 22:
            for j in range(1, int(len(df_22.columns)/time_points+1)):
                column_idex = i + (k * j) - k
                columns_name22.append(df_22.columns[column_idex][0] + '_'+ str(df_22.columns[column_idex][1]))
print(columns_name21)

['RID', 'F1_0', 'F2_0', 'F3_0', 'F4_0', 'F5_0', 'F6_0', 'F7_0', 'F8_0', 'DX_0', 'F1_6', 'F2_6', 'F3_6', 'F4_6', 'F5_6', 'F6_6', 'F7_6', 'F8_6', 'DX_6', 'F1_12', 'F2_12', 'F3_12', 'F4_12', 'F5_12', 'F6_12', 'F7_12', 'F8_12', 'DX_12', 'F1_18', 'F2_18', 'F3_18', 'F4_18', 'F5_18', 'F6_18', 'F7_18', 'F8_18', 'DX_18', 'F1_24', 'F2_24', 'F3_24', 'F4_24', 'F5_24', 'F6_24', 'F7_24', 'F8_24', 'DX_24', 'F1_30', 'F2_30', 'F3_30', 'F4_30', 'F5_30', 'F6_30', 'F7_30', 'F8_30', 'DX_30', 'F1_36', 'F2_36', 'F3_36', 'F4_36', 'F5_36', 'F6_36', 'F7_36', 'F8_36', 'DX_36', 'F1_42', 'F2_42', 'F3_42', 'F4_42', 'F5_42', 'F6_42', 'F7_42', 'F8_42', 'DX_42', 'F1_48', 'F2_48', 'F3_48', 'F4_48', 'F5_48', 'F6_48', 'F7_48', 'F8_48', 'DX_48', 'F1_54', 'F2_54', 'F3_54', 'F4_54', 'F5_54', 'F6_54', 'F7_54', 'F8_54', 'DX_54', 'F1_60', 'F2_60', 'F3_60', 'F4_60', 'F5_60', 'F6_60', 'F7_60', 'F8_60', 'DX_60', 'F1_66', 'F2_66', 'F3_66', 'F4_66', 'F5_66', 'F6_66', 'F7_66', 'F8_66', 'DX_66', 'F1_72', 'F2_72', 'F3_72', 'F4_72', 'F5_72', 'F6_72', 'F7_72', 'F8_72', 'DX_72', 'F1_78', 'F2_78', 'F3_78', 'F4_78', 'F5_78', 'F6_78', 'F7_78', 'F8_78', 'DX_78', 'F1_84', 'F2_84', 'F3_84', 'F4_84', 'F5_84', 'F6_84', 'F7_84', 'F8_84', 'DX_84', 'F1_90', 'F2_90', 'F3_90', 'F4_90', 'F5_90', 'F6_90', 'F7_90', 'F8_90', 'DX_90', 'F1_96', 'F2_96', 'F3_96', 'F4_96', 'F5_96', 'F6_96', 'F7_96', 'F8_96', 'DX_96', 'F1_102', 'F2_102', 'F3_102', 'F4_102', 'F5_102', 'F6_102', 'F7_102', 'F8_102', 'DX_102', 'F1_108', 'F2_108', 'F3_108', 'F4_108', 'F5_108', 'F6_108', 'F7_108', 'F8_108', 'DX_108', 'F1_114', 'F2_114', 'F3_114', 'F4_114', 'F5_114', 'F6_114', 'F7_114', 'F8_114', 'DX_114', 'F1_120', 'F2_120', 'F3_120', 'F4_120', 'F5_120', 'F6_120', 'F7_120', 'F8_120', 'DX_120']

In [33]:
print(columns_name20)

['RID', 'F1_0', 'F2_0', 'F3_0', 'F4_0', 'F5_0', 'F6_0', 'F7_0', 'F8_0', 'DX_0', 'F1_6', 'F2_6', 'F3_6', 'F4_6', 'F5_6', 'F6_6', 'F7_6', 'F8_6', 'DX_6', 'F1_12', 'F2_12', 'F3_12', 'F4_12', 'F5_12', 'F6_12', 'F7_12', 'F8_12', 'DX_12', 'F1_18', 'F2_18', 'F3_18', 'F4_18', 'F5_18', 'F6_18', 'F7_18', 'F8_18', 'DX_18', 'F1_24', 'F2_24', 'F3_24', 'F4_24', 'F5_24', 'F6_24', 'F7_24', 'F8_24', 'DX_24', 'F1_30', 'F2_30', 'F3_30', 'F4_30', 'F5_30', 'F6_30', 'F7_30', 'F8_30', 'DX_30', 'F1_36', 'F2_36', 'F3_36', 'F4_36', 'F5_36', 'F6_36', 'F7_36', 'F8_36', 'DX_36', 'F1_42', 'F2_42', 'F3_42', 'F4_42', 'F5_42', 'F6_42', 'F7_42', 'F8_42', 'DX_42', 'F1_48', 'F2_48', 'F3_48', 'F4_48', 'F5_48', 'F6_48', 'F7_48', 'F8_48', 'DX_48', 'F1_54', 'F2_54', 'F3_54', 'F4_54', 'F5_54', 'F6_54', 'F7_54', 'F8_54', 'DX_54', 'F1_60', 'F2_60', 'F3_60', 'F4_60', 'F5_60', 'F6_60', 'F7_60', 'F8_60', 'DX_60', 'F1_66', 'F2_66', 'F3_66', 'F4_66', 'F5_66', 'F6_66', 'F7_66', 'F8_66', 'DX_66', 'F1_72', 'F2_72', 'F3_72', 'F4_72', 'F5_72', 'F6_72', 'F7_72', 'F8_72', 'DX_72', 'F1_78', 'F2_78', 'F3_78', 'F4_78', 'F5_78', 'F6_78', 'F7_78', 'F8_78', 'DX_78', 'F1_84', 'F2_84', 'F3_84', 'F4_84', 'F5_84', 'F6_84', 'F7_84', 'F8_84', 'DX_84', 'F1_90', 'F2_90', 'F3_90', 'F4_90', 'F5_90', 'F6_90', 'F7_90', 'F8_90', 'DX_90', 'F1_96', 'F2_96', 'F3_96', 'F4_96', 'F5_96', 'F6_96', 'F7_96', 'F8_96', 'DX_96', 'F1_102', 'F2_102', 'F3_102', 'F4_102', 'F5_102', 'F6_102', 'F7_102', 'F8_102', 'DX_102', 'F1_108', 'F2_108', 'F3_108', 'F4_108', 'F5_108', 'F6_108', 'F7_108', 'F8_108', 'DX_108', 'F1_114', 'F2_114', 'F3_114', 'F4_114', 'F5_114', 'F6_114', 'F7_114', 'F8_114', 'DX_114']

In [34]:
for tp in range(1,23):
    if tp == 1:
        rid1 = df0_1[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df1 = pd.DataFrame(columns = columns_name1)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_1)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_1.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_1.iloc[x, column_idex])
            df1.loc[len(df1)] = new_time_point_data
    elif tp == 2:
        rid1 = df0_2[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df2 = pd.DataFrame(columns = columns_name2)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_2)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_2.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_2.iloc[x, column_idex])
            df2.loc[len(df2)] = new_time_point_data
    elif tp == 3:
        rid1 = df0_3[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df3 = pd.DataFrame(columns = columns_name3)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_3)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_3.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_3.iloc[x, column_idex])
            df3.loc[len(df3)] = new_time_point_data
    elif tp == 4:
        rid1 = df0_4[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df4 = pd.DataFrame(columns = columns_name4)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_4)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_4.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_4.iloc[x, column_idex])
            df4.loc[len(df4)] = new_time_point_data
    elif tp == 5:
        rid1 = df0_5[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df5 = pd.DataFrame(columns = columns_name5)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_5)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_5.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_5.iloc[x, column_idex])
            df5.loc[len(df5)] = new_time_point_data
    elif tp == 6:
        rid1 = df0_6[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df6 = pd.DataFrame(columns = columns_name6)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_6)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_6.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_6.iloc[x, column_idex])
            df6.loc[len(df6)] = new_time_point_data
    elif tp == 7:
        rid1 = df0_7[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df7 = pd.DataFrame(columns = columns_name7)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_7)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_7.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_7.iloc[x, column_idex])
            df7.loc[len(df7)] = new_time_point_data
    elif tp == 8:
        rid1 = df0_8[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df8 = pd.DataFrame(columns = columns_name8)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_8)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_8.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_8.iloc[x, column_idex])
            df8.loc[len(df8)] = new_time_point_data
    elif tp == 9:
        rid1 = df0_9[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df9 = pd.DataFrame(columns = columns_name9)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_9)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_9.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_9.iloc[x, column_idex])
            df9.loc[len(df9)] = new_time_point_data
    elif tp == 10:
        rid1 = df0_10[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df10 = pd.DataFrame(columns = columns_name10)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_10)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_10.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_10.iloc[x, column_idex])
            df10.loc[len(df10)] = new_time_point_data
    elif tp == 11:
        rid1 = df0_11[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df11 = pd.DataFrame(columns = columns_name11)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_11)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_11.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_11.iloc[x, column_idex])
            df11.loc[len(df11)] = new_time_point_data
    elif tp == 12:
        rid1 = df0_12[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df12 = pd.DataFrame(columns = columns_name12)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_12)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_12.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_12.iloc[x, column_idex])
            df12.loc[len(df12)] = new_time_point_data
    elif tp == 13:
        rid1 = df0_13[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df13 = pd.DataFrame(columns = columns_name13)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_13)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_13.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_13.iloc[x, column_idex])
            df13.loc[len(df13)] = new_time_point_data
    elif tp == 14:
        rid1 = df0_14[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df14 = pd.DataFrame(columns = columns_name14)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_14)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_14.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_14.iloc[x, column_idex])
            df14.loc[len(df14)] = new_time_point_data
    elif tp == 15:
        rid1 = df0_15[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df15 = pd.DataFrame(columns = columns_name15)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_15)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_15.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_15.iloc[x, column_idex])
            df15.loc[len(df15)] = new_time_point_data
    elif tp == 16:
        rid1 = df0_16[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df16 = pd.DataFrame(columns = columns_name16)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_16)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_16.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_16.iloc[x, column_idex])
            df16.loc[len(df16)] = new_time_point_data
    elif tp == 17:
        rid1 = df0_17[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df17 = pd.DataFrame(columns = columns_name17)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_17)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_17.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_17.iloc[x, column_idex])
            df17.loc[len(df17)] = new_time_point_data
    elif tp == 18:
        rid1 = df0_18[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df18 = pd.DataFrame(columns = columns_name18)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_18)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_18.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_18.iloc[x, column_idex])
            df18.loc[len(df18)] = new_time_point_data
    elif tp == 19:
        rid1 = df0_19[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df19 = pd.DataFrame(columns = columns_name19)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_19)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_19.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_19.iloc[x, column_idex])
            df19.loc[len(df19)] = new_time_point_data
    elif tp == 20:
        rid1 = df0_20[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df20 = pd.DataFrame(columns = columns_name20)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_20)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_20.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_20.iloc[x, column_idex])
            df20.loc[len(df20)] = new_time_point_data
    elif tp == 21:
        rid1 = df0_21[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df21 = pd.DataFrame(columns = columns_name21)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_21)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_21.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_21.iloc[x, column_idex])
            df21.loc[len(df21)] = new_time_point_data
    elif tp == 22:
        rid1 = df0_22[["RID"]]
        unique_rid1 = rid1.values
        unique_rid1 = np.unique(unique_rid1)
        
        df22 = pd.DataFrame(columns = columns_name22)
        time_points = tp #5 represents the number of time points
        for x in range(len(df_22)):
            new_time_point_data = []
            new_time_point_data.append(unique_rid1[x])
            for i in range(time_points):  #5 represents the number of time points
                for j in range(1, int(len(df_22.columns)/time_points+1)):
                    column_idex = i + (tp * j) - tp
                    new_time_point_data.append(df_22.iloc[x, column_idex])
            df22.loc[len(df22)] = new_time_point_data
df21

,RID,F1_0,F2_0,F3_0,F4_0,F5_0,F6_0,F7_0,F8_0,DX_0,...,DX_114,F1_120,F2_120,F3_120,F4_120,F5_120,F6_120,F7_120,F8_120,DX_120
0,377,0.0,0.0,0.0,0.0,4.617186,2.326354,4.631772,0.0,MCI,...,MCI,0.0,0.0,0.032128,0.040235,3.133694,0.905081,3.393676,0.0,MCI

In [35]:
df5

,RID,F1_0,F2_0,F3_0,F4_0,F5_0,F6_0,F7_0,F8_0,DX_0,...,DX_18,F1_24,F2_24,F3_24,F4_24,F5_24,F6_24,F7_24,F8_24,DX_24
0,61,0.0,0.0,0.000000,0.000000,2.625451,0.451596,2.826103,0.0,MCI,...,Dementia,0.0,0.0,2.337421,1.755644,2.423869,0.317885,2.306766,0.0,Dementia
1,83,0.0,0.0,1.683770,2.412149,1.217322,0.239229,1.438654,0.0,Dementia,...,Dementia,0.0,0.0,2.283407,3.026577,0.964684,0.084320,0.352343,0.0,Dementia
2,88,0.0,0.0,1.787197,3.427874,2.623933,1.013995,1.610722,0.0,Dementia,...,Dementia,0.0,0.0,1.787656,3.545444,0.696695,0.000000,0.000000,0.0,Dementia
3,93,0.0,0.0,2.008559,3.249312,2.058195,0.532656,0.994445,0.0,Dementia,...,Dementia,0.0,0.0,2.099237,3.664424,1.401487,0.276822,0.000000,0.0,Dementia
4,149,0.0,0.0,2.926894,3.349094,1.661439,0.308529,1.504524,0.0,Dementia,...,Dementia,0.0,0.0,2.903605,3.717997,1.777509,0.443191,1.207700,0.0,Dementia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,4879,0.0,0.0,3.248373,4.758937,2.687444,1.043125,2.751636,0.0,Dementia,...,Dementia,0.0,0.0,2.384928,3.392260,1.811033,0.544984,1.530271,0.0,Dementia
60,4905,0.0,0.0,1.720203,2.313898,1.476543,0.327722,1.368555,0.0,Dementia,...,Dementia,0.0,0.0,2.154070,3.170650,1.654822,0.474758,1.331927,0.0,Dementia
61,4912,0.0,0.0,1.638499,0.704276,2.091365,0.224786,2.447297,0.0,Dementia,...,Dementia,0.0,0.0,2.034694,3.053215,1.577234,0.438374,1.234365,0.0,Dementia
62,4925,0.0,0.0,0.000000,0.000000,2.048754,0.468393,1.672984,0.0,MCI,...,MCI,0.0,0.0,2.463216,2.091991,0.492973,0.000000,0.263494,0.0,MCI
63,5031,0.0,0.0,0.734477,0.008533,1.924070,0.000000,2.208519,0.0,MCI,...,Dementia,0.0,0.0,1.896401,1.835425,2.016499,0.139497,1.510059,0.0,Dementia

In [36]:
def converter_vs_noconverter(df):
    #num_of_features = 18
    columns_name = list(df.columns)
    # to apply one hot encoding            
    temp_data = df.values
    new_dataset = np.empty((temp_data.shape[0], temp_data.shape[1]))# two extra columns for each time point
    for i in range(new_dataset.shape[0]):
        for j in range(temp_data.shape[1]):
            if (str(temp_data[i, j]) == 'MCI' or str(temp_data[i, j]) == 'Dementia'):
                if str(temp_data[i, j]) == 'MCI':
                    new_dataset[i, j] = 0
                if str(temp_data[i, j]) == 'Dementia':
                    new_dataset[i, j] = 1
            else:
                new_dataset[i, j] = temp_data[i, j]
    
    new_df = pd.DataFrame(new_dataset, columns = columns_name)

    return new_df


df1 = converter_vs_noconverter(df1)
df2 = converter_vs_noconverter(df2)
df3 = converter_vs_noconverter(df3)
df4 = converter_vs_noconverter(df4)
df5 = converter_vs_noconverter(df5)
df6 = converter_vs_noconverter(df6)
df7 = converter_vs_noconverter(df7)
df8 = converter_vs_noconverter(df8)
df9 = converter_vs_noconverter(df9)
df10 = converter_vs_noconverter(df10)
df11 = converter_vs_noconverter(df11)
df12 = converter_vs_noconverter(df12)
df13 = converter_vs_noconverter(df13)
df14 = converter_vs_noconverter(df14)
df15 = converter_vs_noconverter(df15)
df16 = converter_vs_noconverter(df16)
df17 = converter_vs_noconverter(df17)
df18 = converter_vs_noconverter(df18)
df19 = converter_vs_noconverter(df19)
df20 = converter_vs_noconverter(df20)
df21 = converter_vs_noconverter(df21)
#df22 = converter_vs_noconverter(df22)

In [37]:
df5

,RID,F1_0,F2_0,F3_0,F4_0,F5_0,F6_0,F7_0,F8_0,DX_0,...,DX_18,F1_24,F2_24,F3_24,F4_24,F5_24,F6_24,F7_24,F8_24,DX_24
0,61.0,0.0,0.0,0.000000,0.000000,2.625451,0.451596,2.826103,0.0,0.0,...,1.0,0.0,0.0,2.337421,1.755644,2.423869,0.317885,2.306766,0.0,1.0
1,83.0,0.0,0.0,1.683770,2.412149,1.217322,0.239229,1.438654,0.0,1.0,...,1.0,0.0,0.0,2.283407,3.026577,0.964684,0.084320,0.352343,0.0,1.0
2,88.0,0.0,0.0,1.787197,3.427874,2.623933,1.013995,1.610722,0.0,1.0,...,1.0,0.0,0.0,1.787656,3.545444,0.696695,0.000000,0.000000,0.0,1.0
3,93.0,0.0,0.0,2.008559,3.249312,2.058195,0.532656,0.994445,0.0,1.0,...,1.0,0.0,0.0,2.099237,3.664424,1.401487,0.276822,0.000000,0.0,1.0
4,149.0,0.0,0.0,2.926894,3.349094,1.661439,0.308529,1.504524,0.0,1.0,...,1.0,0.0,0.0,2.903605,3.717997,1.777509,0.443191,1.207700,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,4879.0,0.0,0.0,3.248373,4.758937,2.687444,1.043125,2.751636,0.0,1.0,...,1.0,0.0,0.0,2.384928,3.392260,1.811033,0.544984,1.530271,0.0,1.0
60,4905.0,0.0,0.0,1.720203,2.313898,1.476543,0.327722,1.368555,0.0,1.0,...,1.0,0.0,0.0,2.154070,3.170650,1.654822,0.474758,1.331927,0.0,1.0
61,4912.0,0.0,0.0,1.638499,0.704276,2.091365,0.224786,2.447297,0.0,1.0,...,1.0,0.0,0.0,2.034694,3.053215,1.577234,0.438374,1.234365,0.0,1.0
62,4925.0,0.0,0.0,0.000000,0.000000,2.048754,0.468393,1.672984,0.0,0.0,...,0.0,0.0,0.0,2.463216,2.091991,0.492973,0.000000,0.263494,0.0,0.0
63,5031.0,0.0,0.0,0.734477,0.008533,1.924070,0.000000,2.208519,0.0,0.0,...,1.0,0.0,0.0,1.896401,1.835425,2.016499,0.139497,1.510059,0.0,1.0

In [38]:
'''
df1.to_csv('ADNI_Time_Points_1_Train.csv', index = False)
df2.to_csv('ADNI_Time_Points_2_Train.csv', index = False)
df3.to_csv('ADNI_Time_Points_3_Train.csv', index = False)
df4.to_csv('ADNI_Time_Points_4_Train.csv', index = False)
df5.to_csv('ADNI_Time_Points_5_Train.csv', index = False)
df6.to_csv('ADNI_Time_Points_6_Train.csv', index = False)
df7.to_csv('ADNI_Time_Points_7_Train.csv', index = False)
df8.to_csv('ADNI_Time_Points_8_Train.csv', index = False)
df9.to_csv('ADNI_Time_Points_9_Train.csv', index = False)
df10.to_csv('ADNI_Time_Points_10_Train.csv', index = False)
df11.to_csv('ADNI_Time_Points_11_Train.csv', index = False)
df12.to_csv('ADNI_Time_Points_12_Train.csv', index = False)
df13.to_csv('ADNI_Time_Points_13_Train.csv', index = False)
df14.to_csv('ADNI_Time_Points_14_Train.csv', index = False)
df15.to_csv('ADNI_Time_Points_15_Train.csv', index = False)
df16.to_csv('ADNI_Time_Points_16_Train.csv', index = False)
df17.to_csv('ADNI_Time_Points_17_Train.csv', index = False)
df18.to_csv('ADNI_Time_Points_18_Train.csv', index = False)
df19.to_csv('ADNI_Time_Points_19_Train.csv', index = False)
df20.to_csv('ADNI_Time_Points_20_Train.csv', index = False)
df21.to_csv('ADNI_Time_Points_21_Train.csv', index = False)
df22.to_csv('ADNI_Time_Points_22_Train.csv', index = False)
'''

"\ndf1.to_csv('ADNI_Time_Points_1_Train.csv', index = False)\ndf2.to_csv('ADNI_Time_Points_2_Train.csv', index = False)\ndf3.to_csv('ADNI_Time_Points_3_Train.csv', index = False)\ndf4.to_csv('ADNI_Time_Points_4_Train.csv', index = False)\ndf5.to_csv('ADNI_Time_Points_5_Train.csv', index = False)\ndf6.to_csv('ADNI_Time_Points_6_Train.csv', index = False)\ndf7.to_csv('ADNI_Time_Points_7_Train.csv', index = False)\ndf8.to_csv('ADNI_Time_Points_8_Train.csv', index = False)\ndf9.to_csv('ADNI_Time_Points_9_Train.csv', index = False)\ndf10.to_csv('ADNI_Time_Points_10_Train.csv', index = False)\ndf11.to_csv('ADNI_Time_Points_11_Train.csv', index = False)\ndf12.to_csv('ADNI_Time_Points_12_Train.csv', index = False)\ndf13.to_csv('ADNI_Time_Points_13_Train.csv', index = False)\ndf14.to_csv('ADNI_Time_Points_14_Train.csv', index = False)\ndf15.to_csv('ADNI_Time_Points_15_Train.csv', index = False)\ndf16.to_csv('ADNI_Time_Points_16_Train.csv', index = False)\ndf17.to_csv('ADNI_Time_Points_17_Train.csv', index = False)\ndf18.to_csv('ADNI_Time_Points_18_Train.csv', index = False)\ndf19.to_csv('ADNI_Time_Points_19_Train.csv', index = False)\ndf20.to_csv('ADNI_Time_Points_20_Train.csv', index = False)\ndf21.to_csv('ADNI_Time_Points_21_Train.csv', index = False)\ndf22.to_csv('ADNI_Time_Points_22_Train.csv', index = False)\n"

In [39]:

df1.to_csv('ADNI_Time_Points_1_Test.csv', index = False)
df2.to_csv('ADNI_Time_Points_2_Test.csv', index = False)
df3.to_csv('ADNI_Time_Points_3_Test.csv', index = False)
df4.to_csv('ADNI_Time_Points_4_Test.csv', index = False)
df5.to_csv('ADNI_Time_Points_5_Test.csv', index = False)
df6.to_csv('ADNI_Time_Points_6_Test.csv', index = False)
df7.to_csv('ADNI_Time_Points_7_Test.csv', index = False)
df8.to_csv('ADNI_Time_Points_8_Test.csv', index = False)
df9.to_csv('ADNI_Time_Points_9_Test.csv', index = False)
df10.to_csv('ADNI_Time_Points_10_Test.csv', index = False)
df11.to_csv('ADNI_Time_Points_11_Test.csv', index = False)
df12.to_csv('ADNI_Time_Points_12_Test.csv', index = False)
df13.to_csv('ADNI_Time_Points_13_Test.csv', index = False)
df14.to_csv('ADNI_Time_Points_14_Test.csv', index = False)
df15.to_csv('ADNI_Time_Points_15_Test.csv', index = False)
df16.to_csv('ADNI_Time_Points_16_Test.csv', index = False)
df17.to_csv('ADNI_Time_Points_17_Test.csv', index = False)
df18.to_csv('ADNI_Time_Points_18_Test.csv', index = False)
df19.to_csv('ADNI_Time_Points_19_Test.csv', index = False)
df20.to_csv('ADNI_Time_Points_20_Test.csv', index = False)
df21.to_csv('ADNI_Time_Points_21_Test.csv', index = False)
df22.to_csv('ADNI_Time_Points_22_Test.csv', index = False)

In [40]:
'''
df1.to_csv('ADNI_Z_Time_Points_1.csv', index = False)
df2.to_csv('ADNI_Z_Time_Points_2.csv', index = False)
df3.to_csv('ADNI_Z_Time_Points_3.csv', index = False)
df4.to_csv('ADNI_Z_Time_Points_4.csv', index = False)
df5.to_csv('ADNI_Z_Time_Points_5.csv', index = False)
df6.to_csv('ADNI_Z_Time_Points_6.csv', index = False)
df7.to_csv('ADNI_Z_Time_Points_7.csv', index = False)
df8.to_csv('ADNI_Z_Time_Points_8.csv', index = False)
df9.to_csv('ADNI_Z_Time_Points_9.csv', index = False)
df10.to_csv('ADNI_Z_Time_Points_10.csv', index = False)
df11.to_csv('ADNI_Z_Time_Points_11.csv', index = False)
df12.to_csv('ADNI_Z_Time_Points_12.csv', index = False)
df13.to_csv('ADNI_Z_Time_Points_13.csv', index = False)
df14.to_csv('ADNI_Z_Time_Points_14.csv', index = False)
df15.to_csv('ADNI_Z_Time_Points_15.csv', index = False)
df16.to_csv('ADNI_Z_Time_Points_16.csv', index = False)
df17.to_csv('ADNI_Z_Time_Points_17.csv', index = False)
df18.to_csv('ADNI_Z_Time_Points_18.csv', index = False)
df19.to_csv('ADNI_Z_Time_Points_19.csv', index = False)
df20.to_csv('ADNI_Z_Time_Points_20.csv', index = False)
df21.to_csv('ADNI_Z_Time_Points_21.csv', index = False)
df22.to_csv('ADNI_Z_Time_Points_22.csv', index = False)
'''

"\ndf1.to_csv('ADNI_Z_Time_Points_1.csv', index = False)\ndf2.to_csv('ADNI_Z_Time_Points_2.csv', index = False)\ndf3.to_csv('ADNI_Z_Time_Points_3.csv', index = False)\ndf4.to_csv('ADNI_Z_Time_Points_4.csv', index = False)\ndf5.to_csv('ADNI_Z_Time_Points_5.csv', index = False)\ndf6.to_csv('ADNI_Z_Time_Points_6.csv', index = False)\ndf7.to_csv('ADNI_Z_Time_Points_7.csv', index = False)\ndf8.to_csv('ADNI_Z_Time_Points_8.csv', index = False)\ndf9.to_csv('ADNI_Z_Time_Points_9.csv', index = False)\ndf10.to_csv('ADNI_Z_Time_Points_10.csv', index = False)\ndf11.to_csv('ADNI_Z_Time_Points_11.csv', index = False)\ndf12.to_csv('ADNI_Z_Time_Points_12.csv', index = False)\ndf13.to_csv('ADNI_Z_Time_Points_13.csv', index = False)\ndf14.to_csv('ADNI_Z_Time_Points_14.csv', index = False)\ndf15.to_csv('ADNI_Z_Time_Points_15.csv', index = False)\ndf16.to_csv('ADNI_Z_Time_Points_16.csv', index = False)\ndf17.to_csv('ADNI_Z_Time_Points_17.csv', index = False)\ndf18.to_csv('ADNI_Z_Time_Points_18.csv', index = False)\ndf19.to_csv('ADNI_Z_Time_Points_19.csv', index = False)\ndf20.to_csv('ADNI_Z_Time_Points_20.csv', index = False)\ndf21.to_csv('ADNI_Z_Time_Points_21.csv', index = False)\ndf22.to_csv('ADNI_Z_Time_Points_22.csv', index = False)\n"